site_name: RaSDAN Algorithm Documentation - DeepShift Labs
site_url: https://wiki.deepshift.dev
repo_url: https://github.com/DeepShift-Labs/RaSDAN-Algorithm
edit_uri: "https://github.com/DeepShift-Labs/RaSDAN-Algorithm/edit/master/docs" # No need to make changes here if you are using github
site_description: "RaSDAN Algorithm Documentation - DeepShift Labs"
site_author: Krishna Shah
dev_addr: 127.0.0.1:8011


nav:
  - "Read Me": README.md


